#!/usr/bin/env bash
# This script is displaying "Best School" 9 times then hi once

counter=1
while ((counter <= 10))
do
	echo "Best School"
	if ((counter == 9))
	then
		echo "Hi"
	fi
	((counter++))
done
