#!/usr/bin/env bash
# This script is displaying "Best School" 9 times then good luck and bad luck

counter=1
while ((counter <= 10))
do
	if ((counter == 4))
	then
		echo "bad luck"
	elif ((counter == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
