#!/usr/bin/env bash
# This script is displays every minute of every hour.

hour=0
while (( hour <= 12))
do
	echo "Hour: $hour"
	minutes=1
	while (( minutes <= 59))
	do
		echo $minutes
		((minutes++))
	done
	((hour++))
done
